library_core:
  join: backbone-articulation.js
  compress: true
  files:
    - src/**/*.coffee
  modes:
    build:
      commands:
        - 'cp backbone-articulation.js packages/npm/backbone-articulation.js'
        - 'cp backbone-articulation.min.js packages/npm/backbone-articulation.min.js'
        - 'cp backbone-articulation.js packages/nuget/Content/Scripts/backbone-articulation.js'
        - 'cp backbone-articulation.min.js packages/nuget/Content/Scripts/backbone-articulation.min.js'

tests:
  output: build
  directories:
    - test/core
    - test/backbone-relational
    - test/mixin
    - test/packaging
  modes:
    build:
      bundles:
        test/packaging/build/bundle-latest.js:
          underscore: underscore
          backbone: backbone
          backbone-relational: backbone-relational
          json-serialize: json-serialize
          lifecycle: lifecycle
          backbone-articulation: backbone-articulation.js
          _publish:
            underscore: _
            backbone: Backbone

        test/packaging/build/bundle-legacy.js:
          underscore: vendor/underscore-1.0.3.js
          backbone: vendor/backbone-0.5.1.js
          backbone-relational: backbone-relational
          json-serialize: json-serialize
          lifecycle: lifecycle
          backbone-articulation: backbone-articulation.js
          _publish:
            underscore: _
            backbone: Backbone

      no_files_ok: ['test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'

postinstall:
  commands:
    - 'cp underscore vendor/underscore-latest.js'
    - 'cp backbone vendor/backbone-latest.js'
    - 'cp backbone-relational vendor/backbone-relational-latest.js'
    - 'cp json-serialize vendor/json-serialize-latest.js'
    - 'cp lifecycle vendor/lifecycle-latest.js'
