library_core:
  join: backbone-articulation.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      directories:
        - test/core
        - test/backbone-relational
        - test/packaging
      files:
        - '**/*.html'

postinstall:
  copy_latest_underscore:
    command: 'cp'
    args: ['underscore', 'vendor/underscore-latest.js']
  copy_latest_backbone:
    command: 'cp'
    args: ['backbone', 'vendor/backbone-latest.js']
  copy_latest_json_serialize:
    command: 'cp'
    args: ['json-serialize', 'vendor/json-serialize-latest.js']
  copy_latest_lifecycle:
    command: 'cp'
    args: ['lifecycle', 'vendor/lifecycle-latest.js']
