library_core:
  join: backbone-articulation.js
  compress: true
  directories:
    - src

tests:
  output: ./build
  directories:
    - test/core
    - test/backbone-relational
    - test/packaging
  options:
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
    build:
      no_files_ok: ['test/core', 'test/packaging', 'test/backbone-relational']

postinstall:
  copy_latest_underscore:
    command: 'cp'
    args: ['underscore', 'vendor/underscore-latest.js']
  copy_latest_backbone:
    command: 'cp'
    args: ['backbone', 'vendor/backbone-latest.js']
  copy_latest_json_serialize:
    command: 'cp'
    args: ['json-serialize', 'vendor/json-serialize-latest.js']
  copy_latest_lifecycle:
    command: 'cp'
    args: ['lifecycle', 'vendor/lifecycle-latest.js']
