library_core:
  join: backbone-articulation.js
  compress: true
  files:
    - src/**/*.coffee

tests:
  output: build
  directories:
    - test/core
    - test/backbone-relational
    - test/packaging
  modes:
    build:
      bundles:
        test/packaging/build/bundle-latest.js:
          underscore: underscore
          backbone: backbone
          json-serialize: json-serialize
          lifecycle: lifecycle
          backbone-articulation: backbone-articulation.js
        test/packaging/build/bundle-legacy.js:
          underscore: vendor/underscore-1.0.3.js
          backbone: vendor/backbone-0.5.1.js
          json-serialize: json-serialize
          lifecycle: lifecycle
          backbone-articulation: backbone-articulation.js
      no_files_ok: ['test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-qunit-runner.js
      files:
        - '**/*.html'

postinstall:
  commands:
    - 'cp underscore vendor/underscore-latest.js'
    - 'cp backbone vendor/backbone-latest.js'
    - 'cp json-serialize vendor/json-serialize-latest.js'
    - 'cp lifecycle vendor/lifecycle-latest.js'
